version: "3"

services:
  backend:
    image: mp5maker/flask-understand
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app